### ISSUE TITLE
fix extreme deadlock

### ISSUE THREAD

**Issue by cauchy1988** [XiaoMi/pegasus-java-client#169]
遇到的问题描述:
1、我们在恶劣的生产机器环境下发现pegasus-java-client可能会发生死锁现象
2、因为我们应用一次取的数据很多，所以我们初始化客户端的时候配置的超时时间很大与sessionResetTimeWindowMs恰好相同
3、于是在生产环境因为各种原因读取发生超时，导致了以下调用逻辑而发生了死锁， 这里为了简化逻辑描述，假设我们刚开始配置了两个异步nio线程， 即 ’asyncWorkers' 设置成2， 这两个线程分别记做 线程-1， 线程-2 ； 然后我们有3个replicaserver，java client初始化的时候 产生的ReplicaSession结构体和replicaserver 1:1 对应， 这里记做 Replicasession1 ， ReplicaSession2， ReplicaSession3； 并且每个 ReplicaSession 在连接对应的replicaserver时，内部的nettychannel会绑定一个nio线程， 这里也为了描述方便，设定对应绑定的关系如下: ReplicaSession1---线程1， ReplicaSession2---线程2， ReplicaSession3---线程1; 发生死锁的流程图如下:
![image](https://user-images.githubusercontent.com/7292411/136924711-06e39036-4973-4b5e-b481-661d64f3a180.png)
4、 如上图， 发生死锁的原因是因为， ReplicaSession.addTimer 的超时流程 会被随机调度到 线程1 或者是 线程2； 然后发生超时后 tryNotifyFailureWithSeqID 方法 会调用closeSession函数来关闭session，但是关闭session的同步操作要在对应的Replicasession里的nettychannel绑定好的线程内部执行的； 于是就可能发生图上的交叉情况 发生死锁；
5、 这个死锁的概率 常规情况应该是概率很小的， 和我司的极限使用 情况有关系
6、给出的修复方法 是在初始化ReplicaSession的时候 就将 超时调度的线程 和 nettychannel线程强制设置成1个， 那么就不会发生上图交叉的情况 而发生死锁了
代码见 同名 pull request

**Comment by Smityz** [comment]
相关PR: https://github.com/XiaoMi/pegasus-java-client/pull/168
感谢你作出的贡献
