### ISSUE TITLE
support client warmup to prepare connections with replica-server

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/pegasus-java-client#26]

**Comment by neverchanje** [comment]
# 方案讨论

1. client 会在 openTable 的时候去拉取路由表，初始化对 replica-server 的连接，所以如果想要 warm up，首先需要让用户提前去 openTable。

调用过程：

- client.openTable(tableName) =>
- clusterManager.openTable(tableName) =>
- new TableHandler(clusterManager, tableName) =>
- queryCfg => tableHandler.initTableConfiguration()，在这里会拉去路由表，初始化对 replica server 的连接

```java
        if (s.session == null || !s.session.getAddress().equals(pc.primary)) {
          // reset to new primary
          s.session = manager_.getReplicaSession(pc.primary);
        }
```

- 这里会调用 getReplicaSession，因为以前没创建过连接，所以就 new ReplicaSession()

```java
  public ReplicaSession(rpc_address address, EventLoopGroup rpcGroup, int socketTimeout) {
    this.address = address;
    this.rpcGroup = rpcGroup;

    final ReplicaSession this_ = this;
    boot = new Bootstrap();
    boot.group(rpcGroup)
        .channel(ClusterManager.getSocketChannelClass())
        .option(ChannelOption.TCP_NODELAY, true)
        .option(ChannelOption.SO_KEEPALIVE, true)
        .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, socketTimeout)
        .handler(
            new ChannelInitializer<SocketChannel>() {
              @Override
              public void initChannel(SocketChannel ch) {
                ChannelPipeline pipeline = ch.pipeline();
                pipeline.addLast("ThriftEncoder", new ThriftFrameEncoder());
                pipeline.addLast("ThriftDecoder", new ThriftFrameDecoder(this_));
                pipeline.addLast("ClientHandler", new ReplicaSession.DefaultHandler());
              }
            });

    this.firstRecentTimedOutMs = new AtomicLong(0);
  }
```

2. 注意这里只是会初始化这个连接的数据结构，不会进行 tcp 3次握手，所以理论上现在这条连接还未完全 “warm up”。我们可以在 `getReplicaSession` 的时候进行 `doConnect`。从而后面的 rpc 可以完全不需要 3 次握手。

**Comment by qinzuoyan** [comment]
上面只是warmup的一方面，即在openTable的时候建立好与MetaServer的connection。实际上完整的warmup应当包括：
* 建立好与MetaServer的connection。
* 获取table的路由表（这里会检查table是否存在等）。
* 根据路由表中各个partition的primary地址（支持backup request之后还应当包括secondary地址），建立好与相关ReplicaServer的connection。

以上过程，实现时有两种方式可以选择：
* 在现在PegasusClientInterface::openTable()接口中增加参数`bool warmup`，用户可以在openTable的时候选择是否进行warmup。
* 在PegasusClientInterface增加warmup()接口，用户可以通过调用改方法来进行warmup。我推荐这种。

在实现上，可以考虑这样：
* 在warmup()实现中，对每个partition，伪造rrdb_get_operator，设置hashKey和sortKey都为""，设置gpid为改partition的gpid，设置超时时间（譬如为1秒），然后通过table.asyncOperate()发送请求，并等待回调。在回调中我们并不care结果，因为我们只关心建立connection这个过程。
* 上面hashKey和gpid不需要保持一致，因为不管server端怎么处理，我们只要把查询发到server端，建立connection的目标就已经达到了。

**Comment by neverchanje** [comment]
@qinzuoyan  你可能误会我的意思，我的思路是这样：

1. 用户需要 warm up，就调用 openTable，这也符合这个接口的语义：打开表，查询表信息，建立好所有的连接，做好准备操作。不需要增加 warm_up 接口。

2. openTable 现在不建立连接，所以我们就在拉完路由表之后，对每个 ReplicaSession 调用 doConnect，全部连接都建立完再返回结果。当然这样 openTable 的耗时会增加，我们可以设置建立全部连接的上限时间在 10ms 以内，超过了就说明有慢节点。

3. 你只是建立连接，不需要发 fake rpc

总结就是对延时敏感的用户，让他们提前调 openTable。延时不敏感的用户随便，反正 openTable 多的那一点建立连接的时间对他们来说也无所谓。

后面会发测试情况。

**Comment by neverchanje** [comment]
# 性能测试

- c3 client to c4 server
- threadcount = 3

## 1. no warm up

 [INSERT: Count=16855, Max=369407, Min=1514, Avg=1752.21, 90=1763, 99=2083, 99.9=2799, 99.99=369407]

[INSERT: Count=16886, Max=370175, Min=1477, Avg=1748.45, 90=1765, 99=2093, 99.9=3007, 99.99=370175] 

[INSERT: Count=16565, Max=371967, Min=1561, Avg=1782.76, 90=1789, 99=2109, 99.9=2791, 99.99=371967] 

## 2. with warm up

[INSERT: Count=16829, Max=76479, Min=1530, Avg=1702.16, 90=1771, 99=2103, 99.9=2649, 99.99=76415]

[INSERT: Count=16901, Max=76991, Min=1514, Avg=1695.04, 90=1754, 99=2071, 99.9=2847, 99.99=76991] 

[INSERT: Count=16889, Max=75647, Min=1475, Avg=1696.52, 90=1782, 99=2053, 99.9=2639, 99.99=75647] 

## 3. no warm up, 1.11.4 client

[INSERT: Count=16719, Max=379391, Min=1510, Avg=1765.85, 90=1783, 99=2101, 99.9=2843, 99.99=379391]

[INSERT: Count=16923, Max=372479, Min=1522, Avg=1745.07, 90=1759, 99=2059, 99.9=2727, 99.99=372479]

[INSERT: Count=16802, Max=372223, Min=1505, Avg=1757.24, 90=1786, 99=2081, 99.9=2763, 99.99=372223] 

## 4. query meta first, 1.11.4 client

[INSERT: Count=17057, Max=77119, Min=1487, Avg=1678.86, 90=1751, 99=2065, 99.9=2831, 99.99=77119]

[INSERT: Count=16767, Max=76479, Min=1525, Avg=1707.85, 90=1784, 99=2065, 99.9=2505, 99.99=76479]

## Conclusion

我们这里只看 Max latency 和 P99.99 latency，可以得出两个结论：

1. 有 query meta (test 2, 4) 的最大延时只有 75ms，而在第一次请求时才 query meta 的最大延时是 370ms，可以看出有 300ms 左右是花在查路由表上。

2. 提前创建连接对延时几乎看不到收益

**Comment by neverchanje** [comment]
# 性能测试 2

上一个实验我们看到提前 doConnect 对延时得不到任何效果，怀疑是 connect 没有实际进行握手，我们这次采用提前做 fake rpc 的方式看看能不能得到明显效果

## 1. 提前 doConnect

[INSERT: Count=16851, Max=73407, Min=1515, Avg=1700.19, 90=1780, 99=2089, 99.9=2707, 99.99=73407]

[INSERT: Count=16521, Max=78911, Min=1537, Avg=1734.18, 90=1809, 99=2129, 99.9=2853, 99.99=78911] 

## 2. 提前 doConnect 并对各个机器发送 fake rpc

针对这个测试，我们分别尝试了几种 case：只对 1 台机器发 fake rpc，只对 2 台机器发 fake rpc，对 3 台机器分别发 fake rpc。最终的结果都是一样。

 [INSERT: Count=16895, Max=67263, Min=1501, Avg=1692.33, 90=1767, 99=2059, 99.9=2765, 99.99=67263]

[INSERT: Count=16598, Max=68479, Min=1516, Avg=1719.16, 90=1784, 99=2127, 99.9=3659, 99.99=68479]

[INSERT: Count=16658, Max=65343, Min=1550, Avg=1715.05, 90=1780, 99=2099, 99.9=3033, 99.99=65311]

## Conclusion

这里另人意外的是，当 client 发出 fake rpc 后，延时立刻降了 10ms 并且可稳定复现。这说明 fake rpc 一定程度能预热连接。但在 ycsb 测试中，如果我们将测试时间延长，我们会看到 max latency 继续下降，说明连接的预热还有优化的空间，时间更长的预热能够让 max latency 下降更多。

```
2019-01-29 14:49:55:688 10 sec: 16662 operations; 1666.2 current ops/sec; est completion in 16 hours 40 minutes [INSERT: Count=16663, Max=76351, Min=1530, Avg=1718.2, 90=1797, 99=2085, 99.9=2587, 99.99=76287] 
2019-01-29 14:50:05:688 20 sec: 34776 operations; 1811.4 current ops/sec; est completion in 15 hours 58 minutes [INSERT: Count=18113, Max=13999, Min=1507, Avg=1652.13, 90=1717, 99=1784, 99.9=1990, 99.99=12871] 
2019-01-29 14:50:15:688 30 sec: 52899 operations; 1812.3 current ops/sec; est completion in 15 hours 44 minutes [INSERT: Count=18125, Max=7959, Min=1505, Avg=1652.08, 90=1716, 99=1789, 99.9=2365, 99.99=6439] 
```

**Comment by qinzuoyan** [comment]
时间更长的预热 是指什么意思？

**Comment by neverchanje** [comment]
# 性能测试 3

最后就测试一下同机房访问的情况（c3 to c3）：

- ping latency： time=0.066 ms，远小于跨机房（1ms）

## 提前不做任何准备

[INSERT: Count=61977, Max=367871, Min=314, Avg=473.58, 90=513, 99=728, 99.9=2109, 99.99=11423] 

## 提前 query meta 但不发 fake rpc，不提前 connect

 [INSERT: Count=63605, Max=75263, Min=314, Avg=448.05, 90=500, 99=692, 99.9=1389, 99.99=34207] 

## 提前 query meta，并提前 connect，但不发 fake rpc

 [INSERT: Count=60577, Max=76095, Min=322, Avg=470.08, 90=521, 99=769, 99.9=3311, 99.99=21807]

## 提前 query meta，并提前 connect，提前发 fake rpc

[INSERT: Count=61062, Max=66303, Min=315, Avg=465, 90=520, 99=751, 99.9=3079, 99.99=7983]

可见即使是在同机房，最大延时也几乎无差别

**Comment by neverchanje** [comment]
> 时间更长的预热 是指什么意思？

@qinzuoyan 就是用户在实际 send rpc 之前，可能先发 30s 的 fake rpc，不过这样有点类似 ddos。我试了一下，效果不一定好。

**Comment by qinzuoyan** [comment]
OK，那基本可以这样：在openTable时提前query-meta、并建立连接，但是不需要发fake rpc。

在openTable的时候，需要进行恰当的错误处理，譬如：
* 如果query-meta失败或者表不存在，则抛出异常；
* 如果和replica-server建立连接失败，可以打印日志，但是不抛出异常。
