### ISSUE TITLE
support backup request on client side

### ISSUE THREAD

**Issue by levy5307** [XiaoMi/pegasus-java-client#84]
The proposal resides in https://github.com/XiaoMi/pegasus/issues/251.

****一、背景****
--------

Backup request功能可以优化业务在服务抖动时读延迟的长尾问题，适合对一致性要求低的用户。

****二、设计****
------------

1.  增加一个配置项，让用户选择是否启用backup request功能。
2.  在ReplicaConfiguration中添加Map<rpc_address, ReplicaSession> allSessions成员，保存所有的session。
3.  在TableHandler::initTableConfiguration中：
    1.  如果没有开启backup request，则只创建primary副本的session连接放入allSessions。
    2.  如果开启了backup reqeust，secondary也同样要创建连接, 将所有创建的session存入allSessions。
4.  在TableHandler::call中：
    1.  如果是写操作，则要沿用已有逻辑，将请求发往primary。
    2.  如果是读操作，则向allSessions中的所有session都发送请求, 只接收最快的response，其他都忽略（backup reqeust未开启时，allSessions中只有primary session，也相当于只向primary发送）。
        1.  增加is_success(boolean类型), 初始状态下为false，表示请求还没有成功返回，并将其传递给TableHandler::onRpcReply。
        2.  如果isEmpty()，说明还没有和该partition建立好连接，则tryQueryMeta并重新建立连接。
5.  在TableHandler::onRpcReply中，处理请求response：
    1.  如果is_success=true，则说明之前已经有response返回了，则直接忽略。
    2.  如果is\_success=false, 说明该response是第一个返回的, 则按照之前的逻辑处理该请求，处理完之后设置is\_success=true。                                                                               

备注：
*   需要对is_success的处理进行加锁。
*   需要对client_operator中添加一个字段，标记是读操作还是写操作。
*   在4和5中，对于是否开启了backup request是透明的，无需添加额外逻辑判断。只需要在3中创建session时做一下判断。

**Comment by neverchanje** [comment]
> 如果是读操作，则向allSessions中的所有session都发送请求, 只接收最快的response，其他都忽略（backup reqeust未开启时，allSessions中只有primary session，也相当于只向primary发送）。

> 增加is_success(boolean类型), 初始状态下为false，表示请求还没有成功返回，并将其传递给TableHandler::onRpcReply。

> 如果isEmpty()，说明还没有和该partition建立好连接，则tryQueryMeta并重新建立连接。

Could you translate the core ideas in English?

Your first idea is to broadcast read requests to all the nodes in a replica group. Apparently this is unacceptable. It will result in 3 times read throughput than previous. The latency will accordingly increase.

**Comment by levy5307** [comment]
There are two ways to implement a backup request.

****1.Hedged requests****

A client first sends one request to the replica believed to be the most appropriate, but then falls back on sending a secondary request after the first request has been outstanding for more than the 95th-percentile(or 99th-percentline, etc) expected latency. The client cancels remaining outstanding requests once the first result is received. This approach limits the additional load to approximately 5%(1%) while substantially shortening the latency tail. This approach limits the additional load to approximately 5% while substantially shortening the latency tail.

This approach limits the benefits to only a small fraction of requests(the tail of the latency distribution).

****2.Tied requests****

the client send the request to two different servers, each tagged with the identity of the other server (“tied”). When a request begins execution, it sends a cancellation message to its counterpart. The corre- sponding request, if still enqueued in the other server, can be aborted imme- diately or deprioritized substantially.

There is another variation in which the request is sent to one server and forwarded to replicas only if the ini- tial server does not have it in its cache and uses cross-server cancellations.

This approach limits the benefits to not only the tail of the latency, but also median latency distribution. But it resulting in higher network load.

**Comment by neverchanje** [comment]
My first choice is "hedge request" because I doubt that the improvement "tied request" brings deserves the complexity for "cross-server cancellation"

**Comment by levy5307** [comment]
It is more effective to send one sencondary randomly than send all of the two secondaries. Because according to performance test, send to all of the two secondaries will increase p95.

**Comment by levy5307** [comment]
|  测试case   | 是否打开backup request  |  读写比  |  读avg  |  读p95  |  读p99  |  读p999  |  读p9999  |  写avg  |  写p95  |  写p99  |  写p999  |  写p9999  |  
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
