### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [XiaoMi/pegasus-java-client#89]
https://github.com/XiaoMi/pegasus-java-client/blob/3b5c0d1ac56166f3fd3ec31a1a0dd5eda43d3dce/src/main/java/com/xiaomi/infra/pegasus/thrift/transport/THttpClient.java#L348

The program can potentially fail to release a system resource.

**Comment by Shuo-Jia** [comment]
This code is from https://github.com/apache/thrift/blob/0.11.0/lib/java/src/org/apache/thrift/transport/THttpClient.java#L348, in latest verson of pegasus, we have set it `maven dependency` and shade it. Maybe you need report it to https://github.com/apache/thrift/tree/master if it does has potentially problen.
